AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  blog

  Sample SAM Template for blog

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Stage:
    Type: String
    Default: dev
  CIDR:
    Type: String
    Default: 10.22.0.0/16

Resources:
  Network:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./net/template.yaml
      Parameters:
        Stage: !Ref Stage
        CIDR: !Ref CIDR
  App:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./app/template.yaml
      Parameters:
        Stage: !Ref Stage
        VpcId: !GetAtt Network.Outputs.VpcId
