AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  blog

  Sample SAM Template for blog

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Stage:
    Type: String
    Default: dev
  CIDR:
    Type: String
    Default: 10.22.0.0/16

Resources:
  Network:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CIDR
      EnableDnsHostnames: true
      EnableDnsSupport: true

Outputs:
  VpcId:
    Value: !Ref Network
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"
